services:
  - type: web
    name: fossedata-render
    env: python
    buildCommand: ./build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GOOGLE_SERVICE_ACCOUNT_BASE64
      - key: GDRIVE_FOLDER_ID
